### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by SuviH** [nullkaaryle/kaarylepeli#1]
Ladattu 5.2.2017, klo 22.12

Koodi on selkeää, esim kuvailevat kommentit ja selkeä nimeäminen edesauttavat tätä.
Työ on edennyt jo tässä vaiheessa melko pitkälle, ja hyvin toimii pelin tämänhetkinen versio.
Testejäkin näyttää olevan hyvin niitä tarvitseville luokille, mutta ainakin käärylepeli-luokan testejä voisi varmaan saada vielä kattavammaksi.
Kääryle-hahmo on mielenkiintoinen ja persoonallinen idea. Hyvää työtä!

**Comment by nullkaaryle** [comment]
@SuviH kiitos katselmoinnista! 
Käärylepeli-luokan testit olivat tosiaan puutteelliset, seuraavassa palautuksessa tilanne on jo vähän parempi. :)
