### ISSUE TITLE
Katselmus 2

### ISSUE THREAD

**Issue by tuppatar** [nullkaaryle/kaarylepeli#2]
Koodit ladattu 15.2. noin kello 19:53.

Pelin käyttöliittymäluokat näyttäisi olevan aika esimerkillisesti toteutettu ja kuvailtu. Kun itselläni on vielä käyttöliittymäluokat sekavina ja toiminnallisuutta löytyy vääristä paikoista, sain tästä myös muutamia vinkkejä mitä voin hyödyntää (tämä kurssin palautteenanto toimii näköjään siis näinkin päin)!

Koodista oli siis hyvin helppo päästä jyvälle. Luokkien väliset yhteydet ovat järkeviä ja luokkia oli juuri ne joiden äkkiä ajateltuna "kuuluisikin" olla. Metodit olivat sopivat pituisia ja koodi oli siistiä. Myös testejä tuntui olevan hyvin kattavasti ja ne mitä katsoin tarkemmin testasivat järkeviä asioita.

Itse koodin osalta on vaikea keksiä parannusehdotuksia. Kuitenkin sisältöä pelissä on varsin vähän, joten jotain voisi keksiä lisää? Vähintään uuden pelin olisi hyvä pystyä aloittamaan ilman ikkunan sulkemista ja uudelleen käynnistystä. Ja vaikka parhaiden pisteiden talteenotto voisi olla yksi idea.

**Comment by nullkaaryle** [comment]
@tuppatar, kiitos katselmoinnista ja kehitysehdotuksista!

Lisäsin juuri tämän viikon palautukseen pelin uudelleenaloituksen ja huippupisteet. Mietin tosi kauan, että mitkä ominaisuudet olisivat tärkeimpiä tällä viikolla, joten oli tosi hauska, että ehdotit juuri noita samoja! Jos käyttäjä ja tekijä ovat samaa mieltä, niin sitten on kaikki hyvin. :)
